### ISSUE TITLE
Error: Cannot find module './_stream_duplex'

### ISSUE THREAD

**Issue by jviotti** [nodejs/readable-stream#119]
I'm suddenly getting the following issue on `readable-stream` when including the Nock module:

```sh
Message:
    Cannot find module './_stream_duplex'
Details:
    code: MODULE_NOT_FOUND
    domain: [object Object]
    domainThrown: true
Stack:
Error: Cannot find module './_stream_duplex'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at BufferList.Writable (/Users/jviotti/Projects/resin/resin-sdk/node_modules/request/node_modules/bl/node_modules/readable-stream/lib/_stream_writable.js:122:16)
  at BufferList.Duplex (/Users/jviotti/Projects/resin/resin-sdk/node_modules/request/node_modules/bl/node_modules/readable-stream/lib/_stream_duplex.js:58:12)
  at new BufferList (/Users/jviotti/Projects/resin/resin-sdk/node_modules/request/node_modules/bl/bl.js:36:16)
  at BufferList (/Users/jviotti/Projects/resin/resin-sdk/node_modules/request/node_modules/bl/bl.js:6:12)
  at Request.onRequestResponse (/Users/jviotti/Projects/resin/resin-sdk/node_modules/request/request.js:1274:20)
  at OverriddenClientRequest.EventEmitter.emit (events.js:95:17)
  at respond (/Users/jviotti/Projects/resin/resin-sdk/node_modules/nock/lib/request_overrider.js:468:13)
  at /Users/jviotti/Projects/resin/resin-sdk/node_modules/nock/lib/request_overrider.js:481:9
```

The issue seems to reside here: https://github.com/iojs/readable-stream/blob/master/lib/_stream_readable.js#L114, but it's not clear to me why yet.

My package is requiring `readable-stream` v1.0.33 (`nock` requires `request`, which requires `bl`, which requires `readable-stream`).

**Comment by jviotti** [comment]
The issue is fixed if I move:

```js
var Duplex = require('./_stream_duplex');
```

[From line 114 to the top of the file](https://github.com/iojs/readable-stream/blob/master/lib/_stream_readable.js#L114), with the other dependencies.

I can send a PR for this, but I first want to understand why the relative path is messed up in order to add a unit test for this.

**Comment by jtemplet** [comment]
I had the same problem and moving the require('./_stream_duplex') to the top of the file worked. 

Any updates on this issue?

**Comment by calvinmetcalf** [comment]
It looks to be an issue with mock-fs tschaub/mock-fs#12

**Comment by reddynr** [comment]
I am getting below error.while run the angular project in dev. Please advise. Thanks

Error: Cannot find module './internal/streams/BufferList'

**Comment by reddynr** [comment]
**@Vojita,**

Iam getting below error. Please advise. Thanks

Error: Cannot find module './internal/streams/BufferList'
