### ISSUE TITLE
Error: Cannot find module './lib/_stream_transform.js'

### ISSUE THREAD

**Issue by ccorcos** [nodejs/readable-stream#159]
```
❯❯❯ browserify -t brfs template.js > tmp.js                                                                                                              
module.js:338
    throw err;
          ^
Error: Cannot find module './lib/_stream_transform.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/chetcorcos/code/web-ux/node_modules/brfs/node_modules/through2/node_modules/readable-stream/transform.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by ccorcos** [comment]
deleted node_modules and reinstalled everything and it seems to work
