### ISSUE TITLE
npm install fails (ENOTEMPTY)

### ISSUE THREAD

**Issue by adamellsworth** [nodejs/readable-stream#195]
EDIT:

This appears to be a known issue with NPM atm:

https://github.com/npm/npm/issues/12196

(also, the default NPM via apt-get is super old)

---

`npm-debug.log`

```bash
127579 error error rolling back Error: ENOTEMPTY, rmdir '/var/www/dashboard/node_modules/browserify/node_modules/readable-stream'
127579 error error rolling back  browserify@12.0.2 { [Error: ENOTEMPTY, rmdir '/var/www/dashboard/node_modules/browserify/node_modules/readable-stream']
127579 error error rolling back   errno: 53,
127579 error error rolling back   code: 'ENOTEMPTY',
127579 error error rolling back   path: '/var/www/dashboard/node_modules/browserify/node_modules/readable-stream' }
127580 error SyntaxError: Unexpected token
127580 error �SKo�@
                   �+Q����s_�B���
                                 �V���L�d��I�T��c'��8����g��~�a
127580 error �u��1��x߈��,o���	���"�LG� ���U�Q�>~�8P�qU\�yj��3c0v ��9�PYm�Fj\��
y�֛`��                                                                            �89��?��_���
     #�lL�����;)黝��
127580 error !4��&�#�I��Lg�T�B�<�~.�>P8��Q [������hsRm:��ٷ$\���ǻo�A���˪u�GY��j㰶?d~��P�3���ӎ�@�)��TЌ���6#h2n�!���i5���(��L��gߧ7�8��I
127580 error 3(C���?��+�ȸ
[�T�Z����:M�MV�zSg��eM���̜��F�o���~"jԴ�ٍ�0������,�xuإ�o�O=�"�)nˢ�
                                                               X�T��\e+]�Yە^C^�z���פA���=�hFZ�,Þ'~�'"MD^>����UYN�Fg=�������#�k�ټ��>�J����g�z�G�K���"����&�)��&Y*��aC�܃���y~��"��ɾ����o�t��r>�ˇb�
127580 error     at Object.parse (native)
127580 error     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
127580 error     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
127580 error     at Request.EventEmitter.emit (events.js:98:17)
127580 error     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
127580 error     at Request.EventEmitter.emit (events.js:117:20)
127580 error     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
127580 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
127580 error     at _stream_readable.js:920:16
127580 error     at process._tickCallback (node.js:415:13)
127581 error If you need help, you may report this log at:
127581 error     <http://github.com/isaacs/npm/issues>
127581 error or email it to:
127581 error     <npm-@googlegroups.com>
127582 error System Linux 3.16.0-30-generic
127583 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
127584 error cwd /var/www/dashboard
127585 error node -v v0.10.25
127586 error npm -v 1.3.10
127587 error type unexpected_token
127588 verbose exit [ 1, true ]
```

**Comment by calvinmetcalf** [comment]
this is an npm issue not a readable stream issue, you should probably upgrade npm and/or yell at your distro to upgrade it's version to not be so old
