### ISSUE TITLE
gulp build somewhow broken

### ISSUE THREAD

**Issue by ErBlack** [nodejs/readable-stream#244]
On version 2.2.* package somehow broken while runing inside a gulp task.

this will be true https://github.com/nodejs/readable-stream/blob/master/lib/_stream_writable.js#L180
realHasInstance will be undefined

so we have an issue:
```
    at Deps.Writable (…/node_modules/readable-stream/lib/_stream_writable.js:205:23)
    at Deps.Duplex (…/node_modules/readable-stream/lib/_stream_duplex.js:44:12)
    at Deps.Transform (…/node_modules/readable-stream/lib/_stream_transform.js:93:10)
    at new Deps (…/node_modules/module-deps/index.js:25:15)
    at Deps (…/node_modules/module-deps/index.js:24:41)
    at Browserify._createDeps (…/node_modules/browserify/index.js:574:12)
    at Browserify._createPipeline (…/node_modules/browserify/index.js:370:24)
    at new Browserify (…/node_modules/browserify/index.js:84:26)
    at Browserify (…/node_modules/browserify/index.js:39:47)
    at null.__buildFunc (…/.enb/techs/browserify.js:15:17)
```

if same code will be run outside gulp task this will be false https://github.com/nodejs/readable-stream/blob/master/lib/_stream_writable.js#L180 , realHasInstance will be function an code will works well

If I find out anything else I will write here.

**Comment by calvinmetcalf** [comment]
We probably need to do a check for Function.prototype[Symbol.hasInstance]

**Comment by ErBlack** [comment]
Yep. It helps. Here you are https://github.com/nodejs/readable-stream/pull/245

**Comment by calvinmetcalf** [comment]
So out of curiosity what is the strange environment that is causing this
because none that we tested on had this issue

**Comment by ErBlack** [comment]
node v5.12.0, npm 3.8.6. Running enb build inside a gulp task.

```
[19:24:07] Using gulpfile /opt/app/gulpfile.js
[19:24:07] Starting 'build'...
19:24:11.436 - build started
19:24:11.516 - [rebuild] [bundles/common/common.bemjson.js] file-provider
19:24:11.517 - [rebuild] [bundles/map/map.bemjson.js] file-provider
19:24:12.661 - [rebuild] [bundles/map/map.levels] levels
19:24:12.662 - [rebuild] [bundles/common/common.levels] levels
19:24:12.663 - [rebuild] [bundles/common/common.bemdecl.js] bemjson-to-bemdecl
19:24:12.664 - [rebuild] [bundles/map/map.bemdecl.js] bemjson-to-bemdecl
19:24:13.213 - [rebuild] [bundles/map/map.deps.js] deps
19:24:13.263 - [rebuild] [bundles/map/map.files] files
19:24:13.265 - [rebuild] [bundles/map/map.dirs] files
19:24:16.032 - [failed] [bundles/map/map.browser.js] browserify
19:24:16.042 - [failed] [bundles/map/map.js] borschik
19:24:16.043 - build failed
[19:24:16] 'build' errored after 8.09 s
[19:24:16] TypeError: Cannot read property 'call' of undefined
    at Deps.Writable (/opt/app/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:205:23)
    at Deps.Duplex (/opt/app/node_modules/browserify/node_modules/readable-stream/lib/_stream_duplex.js:44:12)
    at Deps.Transform (/opt/app/node_modules/browserify/node_modules/readable-stream/lib/_stream_transform.js:93:10)
    at new Deps (/opt/app/node_modules/browserify/node_modules/module-deps/index.js:25:15)
    at Deps (/opt/app/node_modules/browserify/node_modules/module-deps/index.js:24:41)
    at Browserify._createDeps (/opt/app/node_modules/browserify/index.js:574:12)
    at Browserify._createPipeline (/opt/app/node_modules/browserify/index.js:370:24)
    at new Browserify (/opt/app/node_modules/browserify/index.js:84:
```

¯\_(ツ)_/¯

I really can't explain this. Just caught an exception during package build.

**Comment by ErBlack** [comment]
Can you just fix it for me?) I can make some experiments with this issue, but release is awaits.
