### ISSUE TITLE
2.2.10 version write after end broken?

### ISSUE THREAD

**Issue by NicoTexas** [nodejs/readable-stream#287]
Here is the stack trace we got after the update

```
INFO] [17:58:00] Starting 'copy-js-other'...
[INFO] ERR! [ ERROR ]  write after end
[INFO] ERR! [ ERROR ]  Error: write after end
[INFO] ERR! [ ERROR ]      at writeAfterEnd (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:144:12)
[INFO] ERR! [ ERROR ]      at DestroyableTransform.Writable.write (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:192:5)
[INFO] ERR! [ ERROR ]      at DestroyableTransform.ondata (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/readable-stream/lib/_stream_readable.js:572:20)
[INFO] ERR! [ ERROR ]      at emitOne (events.js:96:13)
[INFO] ERR! [ ERROR ]      at DestroyableTransform.emit (events.js:188:7)
[INFO] ERR! [ ERROR ]      at readableAddChunk (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/readable-stream/lib/_stream_readable.js:195:16)
[INFO] ERR! [ ERROR ]      at DestroyableTransform.Readable.push (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/readable-stream/lib/_stream_readable.js:162:10)
[INFO] ERR! [ ERROR ]      at DestroyableTransform.Transform.push (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/readable-stream/lib/_stream_transform.js:145:32)
[INFO] ERR! [ ERROR ]      at afterTransform (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/readable-stream/lib/_stream_transform.js:101:12)
[INFO] ERR! [ ERROR ]      at TransformState.afterTransform (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/readable-stream/lib/_stream_transform.js:79:12)
[INFO] ERR! [ ERROR ]      at DestroyableTransform.noop [as _transform] (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/gulp-merge/node_modules/through2/through2.js:26:3)
[INFO] ERR! [ ERROR ]      at DestroyableTransform.Transform._read (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/readable-stream/lib/_stream_transform.js:184:10)
[INFO] ERR! [ ERROR ]      at DestroyableTransform.Transform._write (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/readable-stream/lib/_stream_transform.js:172:12)
[INFO] ERR! [ ERROR ]      at doWrite (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/readable-stream/lib/_stream_writable.js:279:12)
[INFO] ERR! [ ERROR ]      at writeOrBuffer (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/readable-stream/lib/_stream_writable.js:266:5)
[INFO] ERR! [ ERROR ]      at DestroyableTransform.Writable.write (/data/jenkins/workspace/Feature_Branch_Build/app-web/node_modules/readable-stream/lib/_stream_writable.js:211:11)
```

**Comment by mcollina** [comment]
Can you please upload a snippet to reproduce the error?

**Comment by mcollina** [comment]
Closing for no activity. Feel free to reopen if you think this is still a bug.
