### ISSUE TITLE
Can't install on mips

### ISSUE THREAD

**Issue by suculent** [nodejs/readable-stream#326]
I'm trying to run `npm install .` on mips architecture.

```
root@Omega-3C75:~/thinx-firmware-js-master# npm install .
root@Omega-3C75:~/thinx-firmware-js-master# node index.js 
module.js:327
    throw err;
    ^

Error: Cannot find module './lib/_stream_readable.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/thinx-firmware-js-master/node_modules/mqtt/node_modules/readable-stream/readable.js:12:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
root@Omega-3C75:~/thinx-firmware-js-master# 
```

Because the file `_stream_readable.js` is really not there.

```
root@Omega-3C75:~/thinx-firmware-js-master/node_modules/mqtt/node_modules/readable-stream/lib# ls -la
drwxr-xr-x    2 root     root             0 Mar 22 14:46 .
drwxr-xr-x    4 root     root             0 Mar 22 14:46 ..
-rw-r--r--    1 root     root          3724 Mar  3 16:18 _stream_duplex.js
-rw-r--r--    1 root     root          1738 Feb  9 16:12 _stream_passthrough.js
root@Omega-3C75:~/thinx-firmware-js-master/node_modules/mqtt/node_modules/readable-stream/lib# 
```

**Comment by suculent** [comment]
Seems like issue of using npm itself, fixed with re-installing the readable-stream package.
