### ISSUE TITLE
asyncWrite is not a function

### ISSUE THREAD

**Issue by chenzeZzz** [nodejs/readable-stream#343]
```
Error: /home/dev/backend/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:458
      asyncWrite(afterWrite, stream, state, finished, cb);
      ^

TypeError: asyncWrite is not a function
    at onwrite (/home/dev/backend/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:458:7)
    at WritableState.onwrite (/home/dev/backend/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:169:5)
    at ConcatStream._write (/home/dev/backend/node_modules/concat-stream/index.js:46:3)
    at doWrite (/home/dev/backend/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/dev/backend/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at ConcatStream.Writable.write (/home/dev/backend/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)

    at doRequest (/home/dev/backend/node_modules/sync-request/index.js:27:11)
    at Object.exports.up_host (/home/dev/backend/node_modules/qiniu/qiniu/zone.js:34:15)
    at putReadable (/home/dev/backend/node_modules/qiniu/qiniu/io.js:55:8)
    at Object.putFile (/home/dev/backend/node_modules/qiniu/qiniu/io.js:120:10)
    at /home/dev/backend/app/common/service/qiniu.js:43:26
    at Generator.next (<anonymous>)
    at step (/home/dev/backend/app/common/service/qiniu.js:21:191)
    at /home/dev/backend/app/common/service/qiniu.js:21:437
    at new Promise (<anonymous>)
    at /home/dev/backend/app/common/service/qiniu.js:21:99
    at module.exports.uploadFile (/home/dev/backend/app/common/service/qiniu.js:56:7)
    at /home/dev/backend/app/common/service/qiniu.js:79:26
    at Generator.next (<anonymous>)
    at step (/home/dev/backend/app/common/service/qiniu.js:21:191)
    at /home/dev/backend/app/common/service/qiniu.js:21:437
    at new Promise (<anonymous>)
```
is it causing the issue?
```
var processNextTick = require('process-nextick-args');
var asyncWrite = !process.browser && ['v0.10', 'v0.9.'].indexOf(process.version.slice(0, 5)) === -1 ? setImmediate : processNextTick;
```

the version of node : 8.9.4
npm: 5.6.0

**Comment by mcollina** [comment]
Would you mind posting a script to reproduce?

**Comment by chenzeZzz** [comment]
i used a lib called qiniu, a cdn server sdk

the calling process is qiniu -> sync-request -> concat-stream -> readable-stream
```
import qiniu from 'qiniu';
async uploadFile(uptoken, key, localFile) {
    let deferred = think.defer();
    let extra = new qiniu.io.PutExtra();
    qiniu.io.putFile(uptoken, key, localFile, extra, (err, ret) => {
      if (!err) {
        // 上传成功， 处理返回值(upload suceessfully, return token)
        ret.url = think.config("qiniu").DOMAIN + '/' + ret.key
        console.debug('qiniu upload url:', ret.url);
        deferred.resolve(ret);
      } else {
        // 上传失败， 处理返回代码(upload failed, deal with retun data)
        console.error('上传失败', err);
        deferred.resolve(false);
      }
    });
    return deferred.promise;
  }
```

**Comment by mcollina** [comment]
Would you mind providing a way to reproduce this problem? It looks it might be webpack/babel related!

**Comment by chenzeZzz** [comment]
the code of calling is above，but its no error by manual， the problem is occured when the web server is up on production env,   maybe the babel, but the code is compiled by think-babel before running

**Comment by mcollina** [comment]
I need something that I can run to reproduce the problem.

I would recommend to remove your lock files and node_modules folder and reinstall everythinf.

**Comment by chenzeZzz** [comment]
@mcollina  the node version on my system is v6.11.2, i exec `nvm use stable` before start the server usually and the stable is v8.9.4, but the lib called 'process-nextick-args' u used, it use the origin node version v6.11.2, Will there be any impact

**Comment by mcollina** [comment]
I do not understand what you mean.
Il giorno ven 29 giu 2018 alle 14:17 天堂鸟丶网吧 <notifications@github.com> ha
scritto:
