### ISSUE TITLE
3.0-rc1 missing dep

### ISSUE THREAD

**Issue by mafintosh** [nodejs/readable-stream#347]
Get this error when requiring the latest rc

``` js
> require('readable-stream')
Error: Cannot find module 'babel-runtime/core-js/symbol'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at _load_symbol (/tmp/tmpdir/CoaDof/node_modules/readable-stream/lib/_stream_readable.js:29:43)
```

**Comment by phated** [comment]
I've also commented at https://github.com/nodejs/readable-stream/pull/344#issuecomment-403580815
