### ISSUE TITLE
TypeError: StringDecoder is not a constructor

### ISSUE THREAD

**Issue by ygmpkk** [nodejs/readable-stream#391]
https://github.com/nodejs/readable-stream/blob/master/lib/_stream_readable.js#L326

I use Typescript other module that require('string_decoder/') is not working.

```
TypeError: StringDecoder is not a constructor
    at Request.Object.<anonymous>.Readable.setEncoding (/Users/timothy/Workspace/hacking/zebra/api/node_modules/light-my-request/node_modules/readable-stream/lib/_stream_readable.js:330:33)
    at rawBody (/Users/timothy/Workspace/hacking/zebra/api/node_modules/fastify/lib/contentTypeParser.js:116:9)
    at ContentTypeParser.Object.<anonymous>.ContentTypeParser.run (/Users/timothy/Workspace/hacking/zebra/api/node_modules/fastify/lib/contentTypeParser.js:72:7)
    at handleRequest (/Users/timothy/Workspace/hacking/zebra/api/node_modules/fastify/lib/handleRequest.js:35:33)
    at onRunMiddlewares (/Users/timothy/Workspace/hacking/zebra/api/node_modules/fastify/fastify.js:446:5)
    at Holder.done (/Users/timothy/Workspace/hacking/zebra/api/node_modules/middie/middie.js:90:9)
    at cors (/Users/timothy/Workspace/hacking/zebra/api/node_modules/cors/lib/index.js:188:7)
    at /Users/timothy/Workspace/hacking/zebra/api/node_modules/cors/lib/index.js:224:17
    at originCallback (/Users/timothy/Workspace/hacking/zebra/api/node_modules/cors/lib/index.js:214:15)
    at /Users/timothy/Workspace/hacking/zebra/api/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/Users/timothy/Workspace/hacking/zebra/api/node_modules/cors/lib/index.js:199:9)
    at corsMiddleware (/Users/timothy/Workspace/hacking/zebra/api/node_modules/cors/lib/index.js:204:7)
    at Holder.done (/Users/timothy/Workspace/hacking/zebra/api/node_modules/middie/middie.js:109:11)
    at Object.run (/Users/timothy/Workspace/hacking/zebra/api/node_modules/middie/middie.js:59:12)
    at middlewareCallback (/Users/timothy/Workspace/hacking/zebra/api/node_modules/fastify/fastify.js:432:29)
    at Object.routeHandler [as handler] (/Users/timothy/Workspace/hacking/zebra/api/node_modules/fastify/fastify.js:286:7)
    at Router.lookup (/Users/timothy/Workspace/hacking/zebra/api/node_modules/find-my-way/index.js:323:17)
    at req.prepare (/Users/timothy/Workspace/hacking/zebra/api/node_modules/light-my-request/index.js:72:43)
    at Request.Object.<anonymous>.Request.prepare (/Users/timothy/Workspace/hacking/zebra/api/node_modules/light-my-request/lib/request.js:74:12)
    at inject (/Users/timothy/Workspace/hacking/zebra/api/node_modules/light-my-request/index.js:72:16)
    at ready.err (/Users/timothy/Workspace/hacking/zebra/api/node_modules/fastify/fastify.js:700:16)
    at Object._encapsulateThreeParam (/Users/timothy/Workspace/hacking/zebra/api/node_modules/avvio/boot.js:378:13)
    at Boot.callWithCbOrNextTick (/Users/timothy/Workspace/hacking/zebra/api/node_modules/avvio/boot.js:311:5)
    at release (/Users/timothy/Workspace/hacking/zebra/api/node_modules/fastq/queue.js:127:16)
    at Object.resume (/Users/timothy/Workspace/hacking/zebra/api/node_modules/fastq/queue.js:61:7)
    at Boot.Plugin.loadPlugin.call (/Users/timothy/Workspace/hacking/zebra/api/node_modules/avvio/boot.js:146:20)
    at toLoad.finish (/Users/timothy/Workspace/hacking/zebra/api/node_modules/avvio/plugin.js:169:7)
    at done (/Users/timothy/Workspace/hacking/zebra/api/node_modules/avvio/plugin.js:127:5)
    at check (/Users/timothy/Workspace/hacking/zebra/api/node_modules/avvio/plugin.js:138:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by mcollina** [comment]
Can you please add a script to reproduce?

Il giorno mar 11 dic 2018 alle 13:46 Timothy <notifications@github.com> ha
scritto:

**Comment by mcollina** [comment]
The module is actually working as expected. We don't want to load that module until the very last minute.

It's a jest bug:

```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Request.Object.<anonymous>.Readable.setEncoding (node_modules/readable-stream/lib/_stream_readable.js:326:39)
      at rawBody (node_modules/fastify/lib/contentTypeParser.js:116:9)
      at ContentTypeParser.Object.<anonymous>.ContentTypeParser.run (node_modules/fastify/lib/contentTypeParser.js:72:7)
      at handleRequest (node_modules/fastify/lib/handleRequest.js:35:33)
      at onRunMiddlewares (node_modules/fastify/fastify.js:446:5)
      at middlewareCallback (node_modules/fastify/fastify.js:434:7)
      at Object.routeHandler [as handler] (node_modules/fastify/fastify.js:286:7)
```

**Comment by mcollina** [comment]
It loads the module in node_modules and not the one in core. That makes this module more reliable, mainly because `require('string_decoder')` in core could have semver-major changes. 

Side note, it has been like this for the last 3-4 years.

**Comment by ygmpkk** [comment]
I see. Thank you very much.

**Comment by mcollina** [comment]
One thing that we can do is to load the file at the top.

Please open an issue on jest and tag me there.
