### ISSUE TITLE
Throws error `Cannot read property 'length' of undefined` on Writable.write()

### ISSUE THREAD

**Issue by SimonSimCity** [nodejs/readable-stream#421]
I've discovered today that a library I use happens to use this library, which under a certain circumstance throws the following errors:

```
 Uncaught Exception: TypeError: Cannot read property 'length' of undefined
     at writeOrBuffer (readable-stream/lib/_stream_writable.js:370:42)
     at StreamChopper.Writable.write (readable-stream/lib/_stream_writable.js:303:11)
     at Client._writevCleaned (elastic-apm-http-client/index.js:276:17)
     at processBatch (elastic-apm-http-client/index.js:249:12)
     at Client._writev (elastic-apm-http-client/index.js:267:3)
     at doWrite (readable-stream/lib/_stream_writable.js:405:97)
     at clearBuffer (readable-stream/lib/_stream_writable.js:501:5)
     at onwrite (readable-stream/lib/_stream_writable.js:451:7)
     at WritableState.onwrite (readable-stream/lib/_stream_writable.js:158:5)
     at afterWrite (readable-stream/lib/_stream_writable.js:465:3)
     at onwrite (readable-stream/lib/_stream_writable.js:457:7)
     at WritableState.onwrite (readable-stream/lib/_stream_writable.js:158:5)
     at StreamChopper.ondrain [as _ondrain] (stream-chopper/index.js:59:5)
     at StreamChopper._removeStream (stream-chopper/index.js:182:45)
     at StreamChopper._endStream (stream-chopper/index.js:165:8)
     at StreamChopper._maybeEndTransformSteam (stream-chopper/index.js:137:27)
     at Gzip._stream.on.chunk (stream-chopper/index.js:94:14)
     at emitOne (events.js:121:20)
     at Gzip.emit (events.js:211:7)
     at addChunk (_stream_readable.js:263:12)
     at readableAddChunk (_stream_readable.js:250:11)
     at Gzip.Readable.push (_stream_readable.js:208:10)
     at Gzip.Transform.push (_stream_transform.js:147:32)
     at Zlib.callback (zlib.js:474:14)
```

```
Uncaught Exception: TypeError: Cannot read property 'length' of undefined
    at writeOrBuffer (readable-stream/lib/_stream_writable.js:370:42)
    at StreamChopper.Writable.write (readable-stream/lib/_stream_writable.js:303:11)
    at Client._writevCleaned (elastic-apm-http-client/index.js:276:17)
    at processBatch (elastic-apm-http-client/index.js:249:12)
    at Client._writev (elastic-apm-http-client/index.js:267:3)
    at doWrite (readable-stream/lib/_stream_writable.js:405:97)
    at clearBuffer (readable-stream/lib/_stream_writable.js:501:5)
    at Client.Writable.uncork (readable-stream/lib/_stream_writable.js:317:94)
    at process.nextTick (elastic-apm-http-client/index.js:310:42)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

Both seemingly boiling down to the same bug. Out of the library `elastic-apm-http-client` (I use it in version 8.2.1) I could confirm that it calls the `write()` method and skips the second parameter (https://github.com/elastic/apm-nodejs-http-client/blob/v8.2.1/index.js#L276):

```js
  this._chopper.write(chunk, cb)
```

Is there a possible value you could think of which would lead to this outcome? Interesting to me is also that the stack-trace shows another occurrence of this library further down.

**Comment by mcollina** [comment]
It's very hard to help without a repro. This looks like a bug in the elastic apm client.

@watson might now more.

**Comment by SimonSimCity** [comment]
@mcollina could you give me a hint on what input you would expect this to fail? Is the function `write` e.g. immune against calling it having "null" or "undefined" as `chunk`?

**Comment by vweevers** [comment]
@SimonSimCity See https://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback:

> chunk \[..\] For streams not operating in object mode, chunk must be a string, Buffer or Uint8Array. For object mode streams, chunk may be any JavaScript value other than null.
