### ISSUE TITLE
Error: Callback called multiple times

### ISSUE THREAD

**Issue by Akuukis** [nodejs/readable-stream#422]
### What is the problem? 

I'm using winston library that uses readable-stream. In some random cases (<1%), but consistently, logging via winston throws the following error (https://github.com/winstonjs/winston/issues/1730):

```
Unhandled "error" event. (Error: Callback called multiple times)
      at DerivedLogger.afterTransform (./node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:82:17)
      at DerivedLogger._transform (./node_modules/winston/lib/winston/logger.js:310:7)
      at DerivedLogger.Object.<anonymous>.Transform._read (./node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:177:10)
      at DerivedLogger.Object.<anonymous>.Transform._write (./node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:164:83)
      at doWrite (./node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:405:139)
      at writeOrBuffer (./node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:394:5)
      at DerivedLogger.Object.<anonymous>.Writable.write (./node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:303:11)
      at DerivedLogger.log (./node_modules/winston/lib/winston/logger.js:244:14)
      at DerivedLogger.(anonymous function) [as verbose] (./node_modules/winston/lib/winston/create-logger.js:95:19)
```

### Debugging

I've setup a repro testcase internally that fails consistently all the time. Unfortunately I can't share codebase. After a lot of debugging I found the only difference between succeeding logs and failing logs: that in failing case `_TransformState` contained a lot of `null`s, see screenshot:

![2](https://user-images.githubusercontent.com/7459419/69721667-03489180-111e-11ea-8875-1a77f7ba902f.png)

The most weird part is that from within winston's `_transform` the _TransformState was all right at both succeeding and failing cases, see screenshot:

![1](https://user-images.githubusercontent.com/7459419/69721763-3b4fd480-111e-11ea-87d3-bfdd18e4a418.png)

Maybe there are some tricks with timing? I tried all kinds of sleeps, and debugger also halts for quite a while, but behavior didn't change.

If I hack the error itself like this, everything seems to work
```diff
-    return this.emit('error', new ERR_MULTIPLE_CALLBACK());
+    return;
```

Please advice what other debugging may be useful and how to proceed.

### Details

- _`node -v`_ - v8.16.2 & v10.17.0
- _Operating System?_ - Linux / Ubuntu 18.04.3 LTS
- _Language?_ - TypeScript 3.6.3
- _Environment?_ - Jest
```sh
$ yarn list --pattern='winston|readable-stream'
yarn list v1.19.1
├─ @lerna/conventional-commits@3.16.4
│  ├─ git-raw-commits@2.0.0
│  │  └─ readable-stream@2.3.6
│  └─ readable-stream@3.4.0
├─ archiver@3.1.1
│  ├─ archiver-utils@2.1.0
│  │  └─ readable-stream@2.3.6
│  ├─ compress-commons@2.1.1
│  │  └─ readable-stream@2.3.6
│  └─ readable-stream@3.4.0
├─ cz-customizable@4.0.0
│  └─ winston@2.1.0
├─ htmlparser2@3.10.1
│  └─ readable-stream@3.4.0
├─ pg-native@3.0.0
│  └─ readable-stream@1.0.31
├─ readable-stream@2.3.6
├─ spdy-transport@3.0.0
│  └─ readable-stream@3.4.0
├─ to-readable-stream@1.0.0
├─ winston-transport@4.3.0
└─ winston@3.2.1
   └─ readable-stream@3.4.0
```

**Comment by mcollina** [comment]
This should be handled in Winston, they should add an ‘error’ event handler. I recommend you to open an issue there.
