### ISSUE TITLE
2.3.8 - lib/_stream_writeable.js line 57 ... process not defined

### ISSUE THREAD

**Issue by jschimmoeller** [nodejs/readable-stream#533]
starting getting this error on line 57 ...

`
/*<replacement>*/
var asyncWrite = !process.browser && ['v0.10', 'v0.9.'].indexOf(process.version.slice(0, 5)) > -1 ? setImmediate : pna.nextTick;
/*</replacement>*/
`

when running it throws this error 
![image](https://github.com/nodejs/readable-stream/assets/1423536/8cbf218b-e5e2-4d29-942d-754be9363a2c)

logs:
Uncaught ReferenceError: process is not defined
    at 24558 (_stream_writable.js:57:18)
    at __webpack_require__ (bootstrap:19:32)
    at 12053 (readable-browser.js:4:20)
    at __webpack_require__ (bootstrap:19:32)
    at 8486 (index.js:5:14)
    at __webpack_require__ (bootstrap:19:32)
    at 40662 (index.js:39:12)
    at __webpack_require__ (bootstrap:19:32)
    at 8865 (utilities.js:6:16)
    at __webpack_require__ (bootstrap:19:32)

FYI.. my work around was in my package.json to use :
`  
"overrides": {
    "readable-stream": "3.6.2"
  }
`

**Comment by mcollina** [comment]
Update your library and dependencies. v2 is _extremely old_.
